services:
  frontend:
    build:
      context: ./
      dockerfile: frontend.Dockerfile
    image: so-daq-sequencer-frontend:latest
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      - API_HTTP=http://localhost:8000
      - PUBLIC_PATH=/nextline/
      - API_NAME=test-build

  backend:
    build:
      context: ./
      dockerfile: backend.Dockerfile
    image: so-daq-sequencer:latest
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - NEXTLINE_SCHEDULE__API=http://scheduler:8010/api/v1/schedule/
      - NEXTLINE_SCHEDULE__POLICY={"policy":"dummy","config":{}}

  scheduler:
    build:
      context: ./
      dockerfile: scheduler.Dockerfile
    image: so-daq-sequencer-scheduler:latest
    container_name: scheduler
